export class TopicGenerator {
  constructor() {
    this.topics = [
      // Technology (Original + Expanded)
      "Should artificial intelligence be regulated by governments?",
      "Are electric vehicles better for the environment than hybrid cars?",
      "Should social media platforms be held responsible for user content?",
      "Is remote work more productive than office work?",
      "Should cryptocurrencies replace traditional banking?",
      "Are smartphones making us less social?",
      "Should there be a universal basic income due to automation?",
      "Is online education as effective as in-person learning?",
      "Should self-driving cars be allowed on public roads?",
      "Are video games beneficial for cognitive development?",
      "Should internet access be a basic human right?",
      "Is cloud storage safer than local storage?",
      "Should children under 13 be allowed on social media?",
      "Are smart homes worth the privacy concerns?",
      "Should companies be required to offer remote work options?",
      "Is 5G technology safe for public health?",
      "Should facial recognition technology be banned in public spaces?",
      "Are password managers more secure than memorizing passwords?",
      "Should tech companies be broken up to prevent monopolies?",
      "Is artificial intelligence a threat to human jobs?",
      "Should autonomous weapons be allowed in warfare?",
      "Are digital currencies the future of money?",
      "Should governments have backdoor access to encrypted devices?",
      "Is biometric authentication more secure than passwords?",
      "Should robots have legal rights?",
      "Are deepfakes more harmful than beneficial?",
      "Should gene editing be allowed in humans?",
      "Is virtual reality the future of entertainment?",
      "Should tech companies pay taxes in every country they operate?",
      "Are subscription services better value than one-time purchases?",

      // Environment (Original + Expanded)
      "Should plastic bags be completely banned?",
      "Is nuclear energy a good solution for energy needs?",
      "Should governments mandate recycling programs?",
      "Are paper books better than e-books for the environment?",
      "Should companies be taxed based on carbon emissions?",
      "Is vegetarianism better for the environment?",
      "Should national parks allow commercial development?",
      "Are renewable energy sources cost-effective?",
      "Should single-use plastics be banned worldwide?",
      "Is lab-grown meat a sustainable solution?",
      "Should fast fashion be regulated?",
      "Are electric cars truly environmentally friendly?",
      "Should governments subsidize solar panel installation?",
      "Should countries be penalized for exceeding carbon limits?",
      "Are reusable products always better than disposable ones?",
      "Should animal agriculture be banned?",
      "Should ocean plastic cleanup be funded by plastic producers?",
      "Are carbon offset programs effective?",
      "Should governments ban gas-powered vehicles?",
      "Is overpopulation the biggest environmental threat?",
      "Should rainforest destruction be considered a crime against humanity?",
      "Are biodegradable plastics a real solution?",
      "Should water be considered a commodity or a human right?",

      // Society (Original + Expanded)
      "Should school start times be later for teenagers?",
      "Is homework beneficial for students?",
      "Should voting be mandatory?",
      "Are participation trophies good for children?",
      "Should junk food be taxed?",
      "Is social media good for democracy?",
      "Should college education be free?",
      "Are books better than movies for storytelling?",
      "Should school uniforms be mandatory?",
      "Is handwriting still important in the digital age?",
      "Should the death penalty be abolished?",
      "Are standardized tests fair measures of intelligence?",
      "Should prisoners be allowed to vote?",
      "Is censorship ever justified?",
      "Should parents be licensed before having children?",
      "Are trigger warnings necessary in education?",
      "Should donations to charity be tax-deductible?",
      "Is graffiti art or vandalism?",
      "Should public transport be free?",
      "Are gated communities beneficial for society?",
      "Should jury duty be mandatory?",
      "Is cancel culture beneficial or harmful?",
      "Should historical statues be removed?",
      "Are beauty pageants empowering or degrading?",
      "Should fireworks be banned?",
      "Is multilingualism essential in modern society?",
      "Should parents be held responsible for their children's crimes?",
      "Are dress codes discriminatory?",
      "Should celebrities be role models?",
      "Is traditional media still relevant?",

      // Economics (Original + Expanded)
      "Should the minimum wage be raised?",
      "Are free markets better than regulated markets?",
      "Should wealthy individuals pay higher taxes?",
      "Is capitalism better than socialism?",
      "Should inheritance be taxed?",
      "Are labor unions beneficial for workers?",
      "Should companies be required to share profits with employees?",
      "Should tipping be abolished?",
      "Is a four-day work week economically viable?",
      "Should corporations be legally considered people?",
      "Are unpaid internships ethical?",
      "Should executive pay be capped?",
      "Is globalization good for developing countries?",
      "Should governments bail out failing businesses?",
      "Are cryptocurrency regulations necessary?",
      "Should student loan debt be forgiven?",
      "Is universal basic income feasible?",
      "Should rent control be implemented?",
      "Are credit scores fair indicators of financial responsibility?",
      "Should countries have wealth caps?",
      "Is the gig economy exploitative?",
      "Should child labor laws be more strict globally?",
      "Are economic sanctions effective?",
      "Should there be a maximum wage?",
      "Is inflation always bad for the economy?",

      // Health (Original + Expanded)
      "Should sugary drinks be taxed?",
      "Is organic food worth the extra cost?",
      "Should healthcare be universal?",
      "Are gym memberships worth the money?",
      "Should fast food restaurants display calorie counts?",
      "Is intermittent fasting effective for weight loss?",
      "Should vaccines be mandatory?",
      "Are standing desks better than sitting desks?",
      "Should prescription drug advertising be banned?",
      "Is mental health as important as physical health?",
      "Should organ donation be opt-out instead of opt-in?",
      "Are energy drinks dangerous?",
      "Should plastic surgery be covered by insurance?",
      "Is alternative medicine legitimate?",
      "Should drug testing be mandatory in sports?",
      "Are GMO foods safe to eat?",
      "Should euthanasia be legal?",
      "Is the body positivity movement healthy?",
      "Should health insurance cover fertility treatments?",
      "Are multivitamins necessary?",
      "Should smoking be banned in all public places?",
      "Is telemedicine as effective as in-person visits?",
      "Should employers be required to provide mental health days?",
      "Are juice cleanses beneficial?",
      "Should marijuana be legalized for medical use?",

      // Entertainment (Original + Expanded)
      "Are movie remakes better than original films?",
      "Should esports be considered real sports?",
      "Is streaming better than traditional television?",
      "Are modern music artists as talented as classic artists?",
      "Should museums charge admission fees?",
      "Is reality TV harmful to society?",
      "Are comic book movies oversaturating the film industry?",
      "Should art be censored for offensive content?",
      "Is live music better than recorded music?",
      "Should concert tickets have price caps?",
      "Are video game loot boxes gambling?",
      "Is binge-watching unhealthy?",
      "Should celebrities' personal lives be private?",
      "Are book-to-movie adaptations ever as good?",
      "Should paparazzi be regulated?",
      "Is stand-up comedy going too far?",
      "Should award shows still exist?",
      "Are theme parks worth the cost?",
      "Is dubbing better than subtitles?",
      "Should musicians own their master recordings?",
      "Are influencers real celebrities?",
      "Should theaters ban phones completely?",
      "Is animation just for children?",
      "Should sporting events be more affordable?",
      "Are vinyl records better than digital music?",

      // Philosophy & Ethics (Original + Expanded)
      "Is privacy more important than security?",
      "Should zoos exist?",
      "Is it ethical to use animals for scientific research?",
      "Should extinct species be brought back through cloning?",
      "Is happiness more important than success?",
      "Should humans try to achieve immortality?",
      "Is free will an illusion?",
      "Should we prioritize human needs over animal rights?",
      "Is assisted suicide a human right?",
      "Should AI have moral rights?",
      "Is it ethical to edit human embryos?",
      "Is truth always better than a comforting lie?",
      "Should parents choose their baby's genetic traits?",
      "Is revenge ever justified?",
      "Should we preserve dying languages?",
      "Is moral relativism valid?",
      "Should humans intervene in natural disasters?",
      "Is consciousness unique to biological beings?",
      "Is suffering necessary for growth?",
      "Should endangered species be saved at any cost?",
      "Is transhumanism ethical?",

      // Daily Life (Original + Expanded)
      "Is breakfast the most important meal of the day?",
      "Are cats better pets than dogs?",
      "Should people make their beds every morning?",
      "Is coffee better than tea?",
      "Should you dress for the job you want?",
      "Are mornings better than evenings for productivity?",
      "Should children have regular chores?",
      "Is it better to rent or buy a home?",
      "Should you separate colors when doing laundry?",
      "Are to-do lists effective?",
      "Should shoes be removed indoors?",
      "Is meal prepping worth the time?",
      "Should beds have multiple pillows?",
      "Are digital calendars better than paper ones?",
      "Should people take daily multivitamins?",
      "Is showering at night better than in the morning?",
      "Should toilet paper hang over or under?",
      "Are electric toothbrushes better than manual?",
      "Should you make plans in advance or be spontaneous?",
      "Is it better to save or spend money?",
      "Should people own or lease cars?",
      "Are hardwood floors better than carpet?",
      "Should households have pets?",
      "Is batch cooking more efficient?",
      "Should everyone learn to cook?",

      // Education
      "Should students be allowed to grade their teachers?",
      "Is homeschooling better than traditional schooling?",
      "Should cursive writing still be taught?",
      "Are standardized tests necessary?",
      "Should students wear uniforms?",
      "Is year-round schooling more effective?",
      "Should financial literacy be mandatory in schools?",
      "Are letter grades outdated?",
      "Should schools ban homework?",
      "Is private school worth the cost?",
      "Should recess be mandatory for all grades?",
      "Are trade schools undervalued?",
      "Should students learn a second language?",
      "Is online learning the future of education?",
      "Should schools teach coding?",
      "Are textbooks becoming obsolete?",
      "Should college athletes be paid?",
      "Is the Ivy League education worth it?",
      "Should gap years be encouraged?",
      "Are school dress codes necessary?",
      "Should music and art be mandatory?",
      "Is rote memorization still valuable?",
      "Should schools start teaching taxes?",
      "Are group projects beneficial?",
      "Should students choose their own curriculum?",
      "Is vocational training as valuable as university?",
      "Should schools eliminate letter grades?",
      "Are school libraries still necessary?",
      "Should ethics be taught in schools?",
      "Is peer tutoring effective?",

      // Science & Medicine
      "Is gene therapy ethical?",
      "Should animal testing be banned?",
      "Are GMOs safe for consumption?",
      "Should human cloning be allowed?",
      "Is artificial meat sustainable?",
      "Should we use CRISPR on humans?",
      "Are nootropics safe for cognitive enhancement?",
      "Is nuclear fusion the energy of the future?",
      "Should we try to extend human lifespan?",
      "Are robots a threat to healthcare jobs?",
      "Should we bioengineer mosquitoes to eliminate malaria?",
      "Is quantum computing overhyped?",
      "Are stem cells the future of medicine?",
      "Should we create synthetic life?",
      "Is nanotechnology safe?",
      "Are personalized medicines worth the cost?",
      "Should we use AI for medical diagnosis?",
      "Is antibiotic resistance our biggest health threat?",
      "Should we attempt de-extinction?",
      "Are brain-computer interfaces safe?",
      "Should we edit the human germline?",
      "Is gut health overrated?",
      "Should we invest in fusion reactors?",
      "Are probiotics overhyped?",
      "Is telomere therapy anti-aging solution?",

      // Sports & Fitness
      "Should professional athletes be role models?",
      "Is CrossFit dangerous?",
      "Should performance-enhancing drugs be allowed in sports?",
      "Are team sports better than individual sports?",
      "Should college athletes be paid?",
      "Is yoga enough exercise?",
      "Should boxing be banned?",
      "Are running shoes necessary?",
      "Should children specialize in one sport early?",
      "Is weightlifting safe for teenagers?",
      "Should extreme sports be regulated?",
      "Are home workouts as effective as gym workouts?",
      "Should coaches be certified?",
      "Is stretching before exercise necessary?",
      "Should cheerleading be considered a sport?",
      "Are protein supplements necessary?",
      "Should performance-based pay exist in sports?",
      "Is swimming the best overall exercise?",
      "Should high contact sports be banned in schools?",
      "Are fitness trackers accurate?",
      "Should esports players train like athletes?",
      "Is cardio more important than strength training?",
      "Should sports betting be legal?",
      "Are recovery days necessary?",
      "Should children be encouraged to play sports?",
      "Is fasted cardio more effective?",
      "Should sports have salary caps?",
      "Are sports drinks necessary?",
      "Should pole dancing be an Olympic sport?",
      "Is morning exercise better than evening?",

      // Food & Nutrition
      "Should schools ban junk food?",
      "Is breakfast really necessary?",
      "Should GMO foods be labeled?",
      "Are meal kits worth the price?",
      "Should restaurants post calorie counts?",
      "Is organic always better?",
      "Should sugar be regulated like tobacco?",
      "Are cheat days healthy?",
      "Should food expiration dates be standardized?",
      "Is bottled water a waste?",
      "Should tipping be mandatory?",
      "Are food delivery apps overpriced?",
      "Should schools provide free lunch?",
      "Is grass-fed beef worth it?",
      "Should energy drinks be age-restricted?",
      "Are superfoods really super?",
      "Should fast food toys be banned?",
      "Is organic milk better?",
      "Should restaurants ban children?",
      "Are food trends just marketing?",
      "Should we eat insects for protein?",
      "Is meal timing important?",
      "Should artificial sweeteners be avoided?",
      "Are food influencers reliable?",
      "Should alcohol advertising be banned?",
      "Is restaurant food too salty?",
      "Should food waste be penalized?",
      "Are farmers markets worth it?",
      "Should fortified foods be mandatory?",
      "Is snacking bad for you?",

      // Travel & Lifestyle
      "Should tourism be limited to protect destinations?",
      "Is travel insurance worth it?",
      "Should airplanes ban reclining seats?",
      "Are hotels better than Airbnb?",
      "Should cruises be banned for environmental reasons?",
      "Is solo travel better than group travel?",
      "Should airlines charge by passenger weight?",
      "Are all-inclusive resorts good value?",
      "Should tourists learn the local language?",
      "Is travel influencer culture harmful?",
      "Should passport restrictions be removed?",
      "Are road trips better than flying?",
      "Should travel be considered educational?",
      "Is dark tourism ethical?",
      "Should airlines separate families with babies?",
      "Are guided tours worth it?",
      "Should travel be more expensive to reduce tourism?",
      "Is voluntourism actually helpful?",
      "Should work-cations be normalized?",
      "Are travel credit cards worth it?",
      "Should airlines overbook flights?",
      "Is backpacking overrated?",
      "Should tourists pay entrance fees to cities?",
      "Are travel vlogs helpful or harmful?",
      "Should countries limit tourist visas?",
      "Is luxury travel wasteful?",
      "Should travel be a human right?",
      "Are digital nomads sustainable?",
      "Should national parks require reservations?",
      "Is overtourism destroying destinations?",

      // Business & Work
      "Should companies have unlimited vacation policies?",
      "Is working from home more productive?",
      "Should dress codes be abolished?",
      "Are open office plans effective?",
      "Should employees be friends on social media?",
      "Is job hopping bad for careers?",
      "Should companies monitor employee emails?",
      "Are performance reviews necessary?",
      "Should everyone have a side hustle?",
      "Is entrepreneurship overrated?",
      "Should companies offer sabbaticals?",
      "Are unpaid internships exploitative?",
      "Should references be abolished?",
      "Is networking more important than skills?",
      "Should salary information be transparent?",
      "Are corporate retreats valuable?",
      "Should employees negotiate salary?",
      "Is employee loyalty dead?",
      "Should companies hire based on culture fit?",
      "Are business degrees necessary?",
      "Should age be removed from resumes?",
      "Is automation killing jobs?",
      "Should companies provide childcare?",
      "Are meetings mostly wasteful?",
      "Should work emails be banned after hours?",
      "Is hustle culture toxic?",
      "Should passion follow money or vice versa?",
      "Are cover letters outdated?",
      "Should companies hire remote-first?",
      "Is the 40-hour work week outdated?",

      // Relationships & Family
      "Should couples share finances?",
      "Is marriage still relevant?",
      "Should parents stay together for the kids?",
      "Are prenuptial agreements unromantic?",
      "Should children be allowed to choose their names?",
      "Is helicopter parenting harmful?",
      "Should grandparents help raise children?",
      "Are traditional gender roles outdated?",
      "Should couples go to bed at the same time?",
      "Is it okay to be friends with exes?",
      "Should parents monitor their teen's phone?",
      "Are open relationships sustainable?",
      "Should couples have separate hobbies?",
      "Is living together before marriage important?",
      "Should family always come first?",
      "Are dating apps ruining romance?",
      "Should parents be honest about Santa?",
      "Is it okay to go to bed angry?",
      "Should couples share passwords?",
      "Are traditional wedding vows outdated?",
      "Should children decide their own bedtime?",
      "Is long-distance worth it?",
      "Should parents be their child's friend?",
      "Are joint social media accounts healthy?",
      "Should couples take separate vacations?",
      "Is the nuclear family model outdated?",
      "Should children be rewarded for good grades?",
      "Are age gaps in relationships problematic?",
      "Should pet ownership be a joint decision?",
      "Is quality time more important than quantity?",

      // Money & Finance
      "Should credit cards be avoided?",
      "Is investing in the stock market gambling?",
      "Should everyone have an emergency fund?",
      "Are financial advisors worth the cost?",
      "Should you pay off debt or save first?",
      "Is buying a house always a good investment?",
      "Should children receive allowances?",
      "Are cryptocurrency investments too risky?",
      "Should you save for retirement or live now?",
      "Is budgeting restrictive or freeing?",
      "Should couples keep finances separate?",
      "Are index funds better than active investing?",
      "Should everyone have a credit card?",
      "Is car leasing smarter than buying?",
      "Should you invest in gold?",
      "Are extended warranties worth it?",
      "Should you pay for financial education?",
      "Is early retirement realistic?",
      "Should students work while in college?",
      "Are insurance products necessary?",
      "Should you invest in real estate?",
      "Is frugality the same as being cheap?",
      "Should inheritance be given early?",
      "Are robo-advisors better than human advisors?",
      "Should you max out your 401k?",

      // Pop Culture & Trends
      "Are influencers real celebrities?",
      "Should celebrities stay out of politics?",
      "Is TikTok harmful to society?",
      "Are fashion trends wasteful?",
      "Should paparazzi be illegal?",
      "Is nostalgia culture holding us back?",
      "Should brands stay neutral on social issues?",
      "Are memes a legitimate form of art?",
      "Is celebrity worship unhealthy?",
      "Should companies use influencers for marketing?",
      "Are podcasts better than traditional radio?",
      "Is fast fashion destroying creativity?",
      "Should celebrities be deplatformed for controversies?",
      "Are subscription boxes worth it?",
      "Is vintage fashion more sustainable?",
      "Should brands apologize for past mistakes?",
      "Are unboxing videos pointless?",
      "Is streetwear art or hype?",
      "Should historical TV shows be historically accurate?",
      "Are reaction videos creative content?",

      // Psychology & Human Behavior
      "Is multitasking effective or harmful?",
      "Should everyone go to therapy?",
      "Are humans naturally good or evil?",
      "Is comparison the thief of joy?",
      "Should you trust your gut instinct?",
      "Are introverts disadvantaged in society?",
      "Is perfectionism holding people back?",
      "Should we teach emotional intelligence in schools?",
      "Are personality tests accurate?",
      "Is social anxiety increasing?",
      "Should mental health days be normalized?",
      "Are humans naturally monogamous?",
      "Is procrastination always bad?",
      "Should we eliminate stigma around medication?",
      "Are negative emotions necessary?",
      "Is imposter syndrome real?",
      "Should everyone journal?",
      "Are comfort zones holding us back?",
      "Is revenge ever satisfying?",
      "Should we separate art from the artist?",

      // Technology & Daily Life Integration
      "Should phones be banned at dinner?",
      "Is digital detox necessary?",
      "Should children have screen time limits?",
      "Are smart speakers invading privacy?",
      "Should you delete old social media posts?",
      "Is blue light filter necessary?",
      "Should schools ban smartphones?",
      "Are digital friendships real?",
      "Should you unfriend people online?",
      "Is FOMO a real problem?",
      "Should you respond to every message?",
      "Are online reviews trustworthy?",
      "Should you Google your date?",
      "Is doom scrolling a real addiction?",
      "Should you post about your relationship?",
      "Are read receipts toxic?",
      "Should workplaces ban personal phone use?",
      "Is it rude to text instead of call?",
      "Should you curate your online presence?",
      "Are group chats overwhelming?",

      // Controversial Yet Balanced Topics
      "Should college be free for everyone?",
      "Is homeschooling better for some children?",
      "Should art require formal education?",
      "Is self-diagnosis ever acceptable?",
      "Should everyone learn to code?",
      "Are participation awards beneficial?",
      "Should history be rewritten to be more inclusive?",
      "Is cultural appropriation always wrong?",
      "Should animals have legal rights?",
      "Is objectivity possible in journalism?",
      "Should wealthy people be obligated to donate?",
      "Are safe spaces necessary?",
      "Should content have trigger warnings?",
      "Is political correctness helpful or harmful?",
      "Should we separate author from their work?",
      "Are meritocracies truly merit-based?",
      "Should reparations be paid for historical wrongs?",
      "Is nuclear family the ideal structure?",
      "Should we preserve traditions?",
      "Is change always progress?",

      // Urban Planning & Infrastructure
      "Should cities ban cars?",
      "Are suburbs environmentally unsustainable?",
      "Should public transport be free?",
      "Is urban sprawl a problem?",
      "Should cities have more green spaces?",
      "Are bike lanes worth the space?",
      "Should cities be designed for walkability?",
      "Is density the solution to housing crises?",
      "Should parking be eliminated?",
      "Are electric scooters a menace?",
      "Should cities invest in public art?",
      "Is brutalist architecture underappreciated?",
      "Should historic buildings be protected?",
      "Are smart cities the future?",
      "Should cities have height restrictions?",
      "Is mixed-use development better?",
      "Should streets be pedestrianized?",
      "Are gated communities harmful?",
      "Should cities ban chain stores?",
      "Is gentrification always negative?",

      // Random Fun & Light Topics
      "Is pineapple on pizza acceptable?",
      "Should you pour milk before cereal?",
      "Are hot dogs sandwiches?",
      "Is a taco a sandwich?",
      "Should toilet paper hang over or under?",
      "Are crocs fashionable?",
      "Is soup a meal?",
      "Should you eat dessert first?",
      "Are fonts important?",
      "Is Comic Sans acceptable?",
      "Should GIFs be pronounced with hard or soft G?",
      "Are adult coloring books valuable?",
      "Is the dress blue or gold?",
      "Should you double-space after periods?",
      "Are fidget spinners useful?",
      "Is ASMR relaxing or creepy?",
      "Should beds have top sheets?",
      "Are crustless sandwiches for children only?",
      "Is ranch dressing overrated?",
      "Should pizza be eaten with hands or utensils?",

      // Ethics in Modern Context
      "Should we have the right to be forgotten online?",
      "Is it ethical to use ad blockers?",
      "Should companies track user data?",
      "Is digital piracy ever justified?",
      "Should genetic information be private?",
      "Are influencer endorsements deceptive?",
      "Should AI art be copyrightable?",
      "Is it wrong to ghost someone?",
      "Should employers check social media?",
      "Are clickbait headlines unethical?",
      "Should you correct strangers' grammar?",
      "Is it rude to not reply to texts?",
      "Should you tip on takeout?",
      "Are gift cards impersonal?",
      "Is regifting acceptable?",
      "Should you give money to panhandlers?",
      "Are white lies necessary?",
      "Should you call out friends' bad behavior?",
      "Is it okay to break minor laws?",
      "Should you return shopping carts?",

      // Sleep & Rest
      "Is 8 hours of sleep necessary?",
      "Should naps be normalized for adults?",
      "Are sleep trackers helpful?",
      "Is sleeping on your back best?",
      "Should bedrooms be technology-free?",
      "Are weighted blankets worth it?",
      "Is snoozing bad for you?",
      "Should everyone have a sleep schedule?",
      "Are sleep studies necessary?",
      "Is melatonin safe long-term?",

      // Personal Development
      "Should everyone have a morning routine?",
      "Is self-help industry actually helpful?",
      "Should you set New Year's resolutions?",
      "Are vision boards effective?",
      "Should everyone meditate?",
      "Is positive thinking enough?",
      "Should you follow your passion?",
      "Are motivational speakers valuable?",
      "Should you read every day?",
      "Is journaling beneficial?",

      // Productivity & Time Management
      "Is waking up early overrated?",
      "Should you batch similar tasks?",
      "Are productivity apps helpful?",
      "Is multitasking possible?",
      "Should you work in 90-minute blocks?",
      "Are deadlines motivating or stressful?",
      "Should you eliminate all distractions?",
      "Is busy-ness a badge of honor?",
      "Should you plan every minute?",
      "Are short breaks or long breaks better?",

      // Communication & Language
      "Should everyone learn public speaking?",
      "Is texting ruining grammar?",
      "Should emojis be used professionally?",
      "Are voice messages better than texts?",
      "Is slang destroying language?",
      "Should you use Oxford commas?",
      "Are audio books real reading?",
      "Is phone calling dying?",
      "Should you proofread casual messages?",
      "Are acronyms getting out of hand?",

      // Pets & Animals
      "Should exotic pets be legal?",
      "Are purebred dogs unethical?",
      "Should pets be allowed in restaurants?",
      "Is pet insurance worth it?",
      "Should you adopt or shop?",
      "Are emotional support animals legitimate?",
      "Should pets sleep in beds?",
      "Is raw food diet better for pets?",
      "Should pets wear clothes?",
      "Are pet birthday parties excessive?",

      // Housing & Living
      "Should you make your bed daily?",
      "Is minimalism practical?",
      "Should homes be shoes-free?",
      "Are tiny houses viable long-term?",
      "Should every room have a purpose?",
      "Is feng shui real?",
      "Should you own or rent furniture?",
      "Are smart homes worth it?",
      "Should bathrooms have windows?",
      "Is white paint the best neutral?",

      // Fashion & Appearance
      "Should makeup be normalized for all genders?",
      "Is fashion art or commerce?",
      "Should dress codes exist?",
      "Are designer brands worth it?",
      "Should you dress for comfort or style?",
      "Is fast fashion ethical?",
      "Should gray hair be dyed?",
      "Are filters harmful?",
      "Should workplaces have dress codes?",
      "Is skincare essential or optional?",

      // Parenting Styles
      "Should parents be strict or lenient?",
      "Is attachment parenting beneficial?",
      "Should children earn their allowance?",
      "Are participation trophies harmful?",
      "Should children be homeschooled?",
      "Is gentle parenting effective?",
      "Should screen time be limited?",
      "Are tiger moms effective?",
      "Should kids be bored sometimes?",
      "Is free-range parenting safe?",

      // Future & Innovation
      "Will AI replace most jobs?",
      "Is immortality desirable?",
      "Will physical money disappear?",
      "Should we prevent aging?",
      "Is fusion energy the future?",
      "Will traditional schooling end?",
      "Is universal basic income inevitable?",
      "Will cars eventually fly?",

      // Environmental Personal Choices
      "Should you avoid single-use items?",
      "Is zero waste achievable?",
      "Should you compost at home?",
      "Are reusable bags always better?",
      "Is veganism necessary?",
      "Should you shop secondhand?",
      "Are electric lawn mowers better?",
      "Should you avoid palm oil?",
      "Is fast furniture a problem?",

      // Career & Professional Development
      "Should you have a five-year plan?",
      "Is personal branding necessary?",
      "Should you job hop for raises?",
      "Are certifications worth it?",
      "Should you work for free exposure?",
      "Is climbing the ladder still relevant?",
      "Should you separate work and personal life?",
      "Are mentors necessary?",
      "Should you negotiate every offer?",
      "Is retirement at 65 outdated?",

      // Social Media Behavior
      "Should you post about your achievements?",
      "Is oversharing a problem?",
      "Should you curate your feed?",
      "Are social media breaks necessary?",
      "Should you accept all friend requests?",
      "Is virtue signaling harmful?",
      "Should you comment or just like?",
      "Are stories better than posts?",
      "Should you follow back everyone?",
      "Is unfollowing rude?",

      // Weather & Seasons
      "Is winter better than summer?",
      "Should we change clocks for daylight saving?",
      "Is rain better than snow?",
      "Should you exercise in extreme heat?",
      "Is seasonal depression real?",
      "Should cities be built for local weather patterns?",
      "Is autumn overrated?",
      "Should snow days exist?",
      "Is spring the best season?",
      "Should we control weather?",

      // Digital Content Creation
      "Should content be free?",
      "Are paywalls fair?",
      "Should creators be paid per view?",
      "Is clickbait ever acceptable?",
      "Should you watermark content?",
      "Are comment sections toxic?",
      "Should platforms censor content?",
      "Is user-generated content valuable?",
      "Should creators respond to comments?",
      "Are shorts/reels devaluing content?",

      // Consumer Behavior
      "Should you always read reviews?",
      "Is buying in bulk always cheaper?",
      "Should you wait for sales?",
      "Are generic brands as good?",
      "Should you support local businesses?",
      "Is impulse buying ever good?",
      "Should you haggle on prices?",
      "Are loyalty programs worth it?",
      "Should you buy extended warranties?",
      "Is price always indicative of quality?",

      // Time & Productivity Philosophy
      "Is being busy productive?",
      "Should you work smarter not harder?",
      "Is perfection the enemy of done?",
      "Is time your most valuable resource?",
      "Should you optimize everything?",
      "Is rest productive?",
      "Should you track your time?",
      "Is slow living possible?",
      "Should you automate everything?",

      // Personal Finance Philosophy
      "Should you live below your means?",
      "Is time or money more valuable?",
      "Should you invest or pay off debt?",
      "Is financial independence the goal?",
      "Should you save for kids' college?",
      "Is experience better than possessions?",
      "Should you keep up with peers financially?",
      "Is being house poor worth it?",
      "Should you buy what you can afford?",
      "Is financial security overrated?",

      // Creativity & Art
      "Should AI-generated art be considered real art?",
      "Is creativity innate or learned?",
      "Should artists starve for their craft?",
      "Is commercial art less valuable?",
      "Should everyone be creative?",
      "Is perfectionism killing creativity?",
      "Should art be accessible to all?",
      "Is critique necessary for growth?",
      "Should artists explain their work?",
      "Is artist suffering romanticized?",

      // Minimalism vs Maximalism
      "Should you own less than 100 things?",
      "Is clutter bad for mental health?",
      "Should you display collections?",
      "Is maximalism making a comeback?",
      "Should you keep sentimental items?",
      "Is capsule wardrobe practical?",
      "Should minimalism be a goal?",
      "Is organization an art form?",
      "Should you use everything you own?",
      "Is excess always wasteful?",

      // Gaming Culture
      "Should games have difficulty settings?",
      "Is gaming a waste of time?",
      "Should parents limit gaming?",
      "Are microtransactions ruining games?",
      "Should games be considered art?",
      "Is competitive gaming healthy?",
      "Should games have story modes?",
      "Are mobile games real games?",
      "Should streamers be regulated?",
      "Is gaming disorder real?",

      // Music & Audio
      "Should music be shuffled or played in order?",
      "Is vinyl really better?",
      "Should concerts ban phones?",
      "Are algorithms discovering good music?",
      "Should you separate artist from music?",
      "Is live music better?",
      "Should you pay for music streaming?",
      "Are playlists better than albums?",
      "Should music be background or focused?",
      "Is louder always better?",

      // Photography & Memories
      "Should you take photos or live in moment?",
      "Is film photography still relevant?",
      "Should you edit all photos?",
      "Are selfies narcissistic?",
      "Should you print digital photos?",
      "Is phone photography real photography?",
      "Should you delete bad photos?",
      "Are posed photos less authentic?",
      "Should memories be documented?",
      "Is nostalgia healthy?",

      // Gift Giving
      "Is cash an acceptable gift?",
      "Should you give practical or fun gifts?",
      "Are gift registries impersonal?",
      "Should experiences be gifts?",
      "Is DIY gifting more meaningful?",
      "Should gifts have receipts?",
      "Are group gifts better?",
      "Should you ask what people want?",
      "Is surprise better than requested?",
      "Should gifts be reciprocal?",

      // Celebration & Holidays
      "Should adults celebrate birthdays?",
      "Is Valentine's Day too commercial?",
      "Should holidays be celebrated traditionally?",
      "Are surprise parties good or bad?",
      "Should you travel for holidays?",
      "Is commercialization ruining holidays?",
      "Should adults believe in Santa Claus narrative?",
      "Are themed parties too much work?",
      "Should milestones be celebrated?",
      "Is New Year's Eve overrated?"
    ];

    this.usedTopics = [];
  }

  generateTopic() {
    // Reset if all topics have been used
    if (this.usedTopics.length >= this.topics.length) {
      this.usedTopics = [];
    }

    // Get unused topics
    const availableTopics = this.topics.filter(topic => !this.usedTopics.includes(topic));

    // Select random topic
    const randomTopic = availableTopics[Math.floor(Math.random() * availableTopics.length)];

    // Mark as used
    this.usedTopics.push(randomTopic);

    return randomTopic;
  }
}
